=== ruboarm/Nokia-XML-Dump-Parser/Sample data/raml20.dtd
<!ELEMENT raml (cmData+) >
<!ATTLIST raml
    version CDATA #FIXED "2.0"
    xmlns CDATA #FIXED "raml20.xsd" >
	<!ELEMENT cmData (header, managedObject*) >
	<!ATTLIST cmData
	type      CDATA #REQUIRED
	scope     CDATA #IMPLIED
	name      CDATA #IMPLIED
	id        CDATA #IMPLIED
	domain    CDATA #IMPLIED  >
	<!ELEMENT header (log+) >
	<!ELEMENT log (#PCDATA) >
	<!ATTLIST log
	dateTime  CDATA #REQUIRED
	action    CDATA #REQUIRED
	user      CDATA #IMPLIED
	appInfo   CDATA #IMPLIED >
	<!ELEMENT managedObject (defaults?, (p | list?)*) >
	<!ATTLIST managedObject
	class     CDATA #REQUIRED
	version   CDATA #IMPLIED
	operation CDATA #IMPLIED
	distName  CDATA #IMPLIED
	id        CDATA #IMPLIED
	name      CDATA #IMPLIED
	vendor    CDATA #IMPLIED
	timeStamp CDATA #IMPLIED>
	<!ELEMENT defaults EMPTY >
	<!ATTLIST defaults
	name      CDATA #REQUIRED
	id        CDATA #IMPLIED
	status    CDATA #IMPLIED >
	<!ELEMENT list (p* , item*) >
	<!ATTLIST list
	name      CDATA #REQUIRED >
	<!ELEMENT item (p*) >
	<!ELEMENT p (#PCDATA) >
	<!ATTLIST p
	name      CDATA #IMPLIED >

=== ruboarm/Nokia-XML-Dump-Parser/Sample data/dump_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE raml SYSTEM 'raml20.dtd'>
<raml version="2.0" xmlns="raml20.xsd">
  <cmData type="actual">
    <header>
      <log dateTime="2021-11-02T14:07:55.000+04:00" action="created" appInfo="ActualExporter">InternalValues are used</log>
    </header>
    <managedObject class="ADJI" version="RNC18" distName="PLMN-PLMN/RNC-3/WBTS-7487/WCEL-6/ADJI-9" id="1881774">
      <p name="AdjiMCC">283</p>
      <p name="AdjiMNC">10</p>
      <p name="TargetCellDN">PLMN-PLMN/EXCCU-1/EXUCE-720</p>
      <p name="name">test1</p>
      <p name="ADJIChangeOrigin">2</p>
      <p name="AdjiCI">8044</p>
      <p name="AdjiCPICHTxPwr">330</p>
      <p name="AdjiComLoadMeasDRNCCellNCHO">0</p>
      <p name="AdjiEcNoOffsetNCHO">12</p>
      <p name="AdjiHandlingBlockedCellSLHO">1</p>
      <p name="AdjiLAC">30110</p>
      <p name="AdjiNCHOHSPASupport">0</p>
      <p name="AdjiRAC">110</p>
      <p name="AdjiRNCid">10</p>
      <p name="AdjiSIB">1</p>
      <p name="AdjiScrCode">374</p>
      <p name="AdjiTxDiv">0</p>
      <p name="AdjiTxPwrDPCH">24</p>
      <p name="AdjiTxPwrRACH">21</p>
      <p name="AdjiUARFCN">10713</p>
      <p name="BlindHOTargetCell">0</p>
      <p name="NrtHopiIdentifier">62</p>
      <p name="RtHopiIdentifier">61</p>
    </managedObject>
    <managedObject class="ADJS" version="RNC18" distName="PLMN-PLMN/RNC-3/WBTS-7487/WCEL-2/ADJS-8" id="1881776">
      <p name="AdjsMCC">283</p>
      <p name="AdjsMNC">10</p>
      <p name="TargetCellDN">PLMN-PLMN/EXCCU-1/EXUCE-720</p>
      <p name="name">test2</p>
      <p name="ADJSChangeOrigin">2</p>
      <p name="AdjsCI">8044</p>
      <p name="AdjsCPICHTxPwr">330</p>
      <p name="AdjsDERR">0</p>
      <p name="AdjsEcNoOffset">0</p>
      <p name="AdjsLAC">30110</p>
      <p name="AdjsRAC">110</p>
      <p name="AdjsRNCid">10</p>
      <p name="AdjsSIB">1</p>
      <p name="AdjsScrCode">374</p>
      <p name="AdjsTxDiv">0</p>
      <p name="AdjsTxPwrRACH">21</p>
      <p name="HSDPAHopsIdentifier">93</p>
      <p name="NrtHopsIdentifier">92</p>
      <p name="RTWithHSDPAHopsIdentifier">94</p>
      <p name="RtHopsIdentifier">91</p>
    </managedObject>
    <managedObject class="EXCCU" version="1.0" distName="PLMN-PLMN/EXCCU-1" id="202950">
      <defaults name="System"/>
    </managedObject>
    <managedObject class="WCEL" version="RNC18" distName="PLMN-PLMN/RNC-543/WBTS-2229/WCEL-1" id="1489496">
      <defaults name="System"/>
      <p name="WCELMCC">283</p>
      <p name="WCELMNC">10</p>
      <p name="name">test3</p>
      <p name="ACBarredList">0</p>
      <p name="AICHTraTime">0</p>
      <p name="AMROverSC">90</p>
      <p name="AMROverTransmission">9</p>
      <p name="AMROverTxNC">-10</p>
      <p name="AMROverTxNonHSPA">0</p>
      <p name="AMROverTxTotal">20</p>
      <p name="AMRSF">-2</p>
      <p name="AMRTargetSC">70</p>
      <p name="AMRTargetTransmission">8</p>
      <p name="AMRTargetTxNC">-20</p>
      <p name="AMRTargetTxNonHSPA">-10</p>
      <p name="AMRTargetTxTotal">0</p>
      <p name="AMRUnderSC">50</p>
      <p name="AMRUnderTransmission">2</p>
      <p name="AMRUnderTxNC">-100</p>
      <p name="AMRUnderTxNonHSPA">-100</p>
      <p name="AMRUnderTxTotal">-100</p>
      <p name="AbsPrioCellReselec">0</p>
      <p name="AdminCellState">1</p>
      <p name="AdminPICState">1</p>
      <p name="AllowedRACHSubChannels">4095</p>
      <p name="AltScramblingCodeCM">0</p>
      <p name="AssignedPICPool">0</p>
      <p name="BlindHOEcNoThrTarget">-24</p>
      <p name="BlindHORSCPThrTarget">-95</p>
      <p name="CCHSetupEnabled">0</p>
      <p name="CIRForFDPCH">-44</p>
      <p name="CId">52295</p>
      <p name="CPCEnabled">0</p>
      <p name="CPICHEcNoSRBMapRRC">-16</p>
      <p name="CPICHRSCPSRBMapRRC">-92</p>
      <p name="CPICHtoRefRABoffset">-20</p>
      <p name="CSAMRModeSET">7</p>
      <p name="CSAMRModeSETWB">1</p>
      <p name="CSGroupId">0</p>
      <p name="CTCHCapaHighPri">0</p>
      <p name="CUCEcNoThreshold">27</p>
      <p name="CUCRSCPThreshold">-92</p>
      <p name="CableLoss">10</p>
      <p name="CellBarred">1</p>
      <p name="CellRange">10000</p>
      <p name="CellSelQualMeas">0</p>
      <p name="CellWeightForHSDPALayering">100</p>
      <p name="Cell_Reserved">1</p>
      <p name="CodeTreeOptTimer">3600</p>
      <p name="CodeTreeOptimisation">1</p>
      <p name="CodeTreeUsage">40</p>
      <p name="DCellHSDPACapaHO">0</p>
      <p name="DCellHSDPAEnabled">1</p>
      <p name="DCellHSDPAFmcsId">97</p>
      <p name="DLLoadStateTTT">4</p>
      <p name="DPCHOverHSPDSCHThreshold">5</p>
      <p name="DPCModeChangeSupport">1</p>
      <p name="DRRCprxMargin">0</p>
      <p name="DRRCprxOffset">-10</p>
      <p name="DRRCptxMargin">-5</p>
      <p name="DRRCptxOffset">-30</p>
      <p name="DeltaPrxMaxDown">10</p>
      <p name="DeltaPrxMaxUp">6</p>
      <p name="DeltaPtxMaxDown">15</p>
      <p name="DeltaPtxMaxUp">8</p>
      <p name="DirectedRRCEnabled">0</p>
      <p name="DirectedRRCForHSDPALayerEnabled">1</p>
      <p name="EDCHCapability">0</p>
      <p name="EDCHMinSetETFCIT0">29</p>
      <p name="EDCHMinimumSetETFCI">4</p>
      <p name="EDCHOpState">0</p>
      <p name="EbNoSetIdentifier">2</p>
      <p name="FDPCHCodeChangeEnabled">6</p>
      <p name="FDPCHEnabled">0</p>
      <p name="FDPCHSetup">0</p>
      <p name="FachLoadMarginCCH">5</p>
      <p name="FachLoadThresholdCCH">75</p>
      <p name="HCS_PRIO">7</p>
      <p name="HHoMaxAllowedBitrateDL">32</p>
      <p name="HHoMaxAllowedBitrateUL">32</p>
      <p name="HSCapabilityHONumbUE">3</p>
      <p name="HSCapabilityHOPeriod">0</p>
      <p name="HSDPA64QAMallowed">1</p>
      <p name="HSDPA64UsersEnabled">0</p>
      <p name="HSDPAFmcgIdentifier">83</p>
      <p name="HSDPAFmciIdentifier">11</p>
      <p name="HSDPAFmcsIdentifier">93</p>
      <p name="HSDPALayeringCommonChEnabled">1</p>
      <p name="HSDPAcapability">0</p>
      <p name="HSDPAenabled">1</p>
      <p name="HSDSCHOpState">0</p>
      <p name="HSFACHActTimeToTrigger">100</p>
      <p name="HSFACHActivityAveWin">1</p>
      <p name="HSFACHActivityThr">16</p>
      <p name="HSFACHCapability">0</p>
      <p name="HSFACHEnabled">0</p>
      <p name="HSFACHRLCTimeToTrigger">200</p>
      <p name="HSFACHRel7ConSetupEC">458124</p>
      <p name="HSFACHVolThrDL">1024</p>
      <p name="HSLoadStateHSDBRLimit">32</p>
      <p name="HSLoadStateHSDOffset">-10</p>
      <p name="HSLoadStateHSUBRLimit">24</p>
      <p name="HSLoadStateHSUOffset">-10</p>
      <p name="HSLoadStateHSUResThr">2</p>
      <p name="HSPA72UsersPerCell">1</p>
      <p name="HSPACapaHO">0</p>
      <p name="HSPAFmcsIdentifier">98</p>
      <p name="HSPAQoSEnabled">2</p>
      <p name="HSPDSCHCodeSet">64800</p>
      <p name="HSPDSCHMarginSF128">1</p>
      <p name="HSUPA2MSTTIEnabled">1</p>
      <p name="HSUPAEnabled">1</p>
      <p name="HspaMultiNrtRabSupport">1</p>
      <p name="IncomingLTEISHO">1</p>
      <p name="InitialBitRateDL">64</p>
      <p name="InitialBitRateUL">16</p>
      <p name="InterFreqScaleTresel">4</p>
      <p name="InterRATScaleTresel">4</p>
      <p name="IntraFreq_Cell_Reselect_Ind">0</p>
      <p name="KforCTCH">0</p>
      <p name="LAC">30106</p>
      <p name="LHOCapaReqRejRateDL">70</p>
      <p name="LHOCapaReqRejRateUL">70</p>
      <p name="LHODelayOFFCapaReqRejRate">30</p>
      <p name="LHODelayOFFHardBlocking">30</p>
      <p name="LHODelayOFFInterference">30</p>
      <p name="LHODelayOFFResRateSC">30</p>
      <p name="LHOHardBlockingBaseLoad">5</p>
      <p name="LHOHardBlockingRatio">10</p>
      <p name="LHOHystTimeCapaReqRejRate">2</p>
      <p name="LHOHystTimeHardBlocking">2</p>
      <p name="LHOHystTimeInterference">2</p>
      <p name="LHOHystTimeResRateSC">2</p>
      <p name="LHONRTTrafficBaseLoad">10</p>
      <p name="LHONumbUEInterFreq">10</p>
      <p name="LHONumbUEInterRAT">0</p>
      <p name="LHOPwrOffsetDL">-15</p>
      <p name="LHOPwrOffsetUL">-7</p>
      <p name="LHOResRateSC">80</p>
      <p name="LHOWinSizeOFFCapaReqRejRate">5</p>
      <p name="LHOWinSizeOFFHardBlocking">5</p>
      <p name="LHOWinSizeOFFInterference">5</p>
      <p name="LHOWinSizeOFFResRateSC">5</p>
      <p name="LHOWinSizeONCapaReqRejRate">0</p>
      <p name="LHOWinSizeONHardBlocking">0</p>
      <p name="LHOWinSizeONInterference">0</p>
      <p name="LHOWinSizeONResRateSC">0</p>
      <p name="LTECellReselection">1</p>
      <p name="LoadBasedCPICHEcNoSRBHSPA">-25</p>
      <p name="LoadBasedCPICHEcNoThreEDCH2MS">-25</p>
      <p name="MBLBEnhancementsEnabled">0</p>
      <p name="MBLBInactivityEnabled">0</p>
      <p name="MBLBLoadInfoDistr">0</p>
      <p name="MBLBMobilityEnabled">0</p>
      <p name="MBLBRABSetupEnabled">1</p>
      <p name="MBLBRABSetupMultiRAB">0</p>
      <p name="MBLBStateTransEnabled">0</p>
      <p name="MHA">0</p>
      <p name="MaxBitRateDLPSNRT">128</p>
      <p name="MaxBitRateULPSNRT">128</p>
      <p name="MaxCodeReleases">40</p>
      <p name="MaxDLPowerCapability">400</p>
      <p name="MaxIncrInterferenceUL">10</p>
      <p name="MaxNbrOfHSSCCHCodes">4</p>
      <p name="MaxNumbHSDPAUsersS">0</p>
      <p name="MaxNumbHSDSCHMACdFS">0</p>
      <p name="MaxNumberEDCHCell">72</p>
      <p name="MaxNumberHSDPAUsers">0</p>
      <p name="MaxNumberHSDSCHMACdFlows">0</p>
      <p name="MaxNumberUECmHO">16</p>
      <p name="MaxNumberUECmSLHO">6</p>
      <p name="MaxNumberUEHSPACmHO">10</p>
      <p name="MaxNumberUEHSPACmNCHO">5</p>
      <p name="MaxTotalUplinkSymbolRate">2</p>
      <p name="MinAllowedBitRateDL">8</p>
      <p name="MinAllowedBitRateUL">8</p>
      <p name="N300">5</p>
      <p name="N312">1</p>
      <p name="N312Conn">2</p>
      <p name="N313">5</p>
      <p name="N315">0</p>
      <p name="NASsignVolThrDL">8</p>
      <p name="NASsignVolThrUL">8</p>
      <p name="NCr">8</p>
      <p name="NbrOfSCCPCHs">1</p>
      <p name="NforCTCH">2</p>
      <p name="NonHCSNcr">8</p>
